/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kapehan;

/**
 *
 * @author Student.admin
 */
public class AddressForm extends javax.swing.JFrame {

    /**
     * Creates new form AddressForm
     */
    public AddressForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        LeftArrowInfoLabel = new javax.swing.JLabel();
        AddressTextArea = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AddressTextArea1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        uncheckedButtonLabel = new javax.swing.JLabel();
        CheckedButtonLabel1 = new javax.swing.JLabel();
        AddNewAddress = new javax.swing.JButton();
        trashinUncheckedbutton = new javax.swing.JLabel();
        TrashbinCheckbutton = new javax.swing.JLabel();
        phoneBackground = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 70, 84, 22);

        LeftArrowInfoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LeftArrowInfoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\ethyl28\\src\\img\\leftArrow.png")); // NOI18N
        LeftArrowInfoLabel.setText("jLabel2");
        getContentPane().add(LeftArrowInfoLabel);
        LeftArrowInfoLabel.setBounds(30, 70, 30, 20);

        AddressTextArea.setBorder(null);
        AddressTextArea.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        AddressTextArea.setHorizontalScrollBar(null);

        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Brgy, Maligalig,DiMatagpuan\nStreet, Mars");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        AddressTextArea.setViewportView(jTextArea1);

        getContentPane().add(AddressTextArea);
        AddressTextArea.setBounds(30, 240, 150, 34);

        AddressTextArea1.setBorder(null);
        AddressTextArea1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        AddressTextArea1.setHorizontalScrollBar(null);

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\nSamjung Building, Nasipit \nRoad,Talamban Cebu City");
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        AddressTextArea1.setViewportView(jTextArea2);

        getContentPane().add(AddressTextArea1);
        AddressTextArea1.setBounds(30, 170, 150, 31);

        uncheckedButtonLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\radio-button-unchecked.png")); // NOI18N
        getContentPane().add(uncheckedButtonLabel);
        uncheckedButtonLabel.setBounds(190, 240, 32, 32);

        CheckedButtonLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\radio-button-checked.png")); // NOI18N
        getContentPane().add(CheckedButtonLabel1);
        CheckedButtonLabel1.setBounds(190, 170, 32, 32);

        AddNewAddress.setBackground(new java.awt.Color(52, 32, 0));
        AddNewAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddNewAddress.setForeground(new java.awt.Color(255, 255, 255));
        AddNewAddress.setText("Add New Address");
        AddNewAddress.setBorder(null);
        AddNewAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNewAddress.setFocusPainted(false);
        AddNewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewAddressActionPerformed(evt);
            }
        });
        getContentPane().add(AddNewAddress);
        AddNewAddress.setBounds(70, 460, 140, 30);

        trashinUncheckedbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\trashbin.png")); // NOI18N
        trashinUncheckedbutton.setText("jLabel2");
        getContentPane().add(trashinUncheckedbutton);
        trashinUncheckedbutton.setBounds(220, 240, 37, 35);

        TrashbinCheckbutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\trashbin.png")); // NOI18N
        TrashbinCheckbutton.setText("jLabel2");
        getContentPane().add(TrashbinCheckbutton);
        TrashbinCheckbutton.setBounds(220, 170, 37, 35);

        phoneBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\ethyl28\\src\\img\\ea7a08282f40760a5989ba022d6f0480-removebg-preview.png")); // NOI18N
        getContentPane().add(phoneBackground);
        phoneBackground.setBounds(0, 20, 280, 540);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 30, 240, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNewAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddressForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddressForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewAddress;
    private javax.swing.JScrollPane AddressTextArea;
    private javax.swing.JScrollPane AddressTextArea1;
    private javax.swing.JLabel CheckedButtonLabel1;
    private javax.swing.JLabel LeftArrowInfoLabel;
    private javax.swing.JLabel TrashbinCheckbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel phoneBackground;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel trashinUncheckedbutton;
    private javax.swing.JLabel uncheckedButtonLabel;
    // End of variables declaration//GEN-END:variables
}
