/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kapehan;
/**
 *
 * @author Student.admin
 */
public class MyInformation_page extends javax.swing.JFrame {

    /**
     * Creates new form MyInformation_page
     */
    public MyInformation_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        MyInformationLabel = new javax.swing.JLabel();
        EditInfoLabel = new javax.swing.JLabel();
        LeftArrowInfoLabel = new javax.swing.JLabel();
        NameLogoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        FullNameLabel = new javax.swing.JLabel();
        InputNameLabel = new javax.swing.JLabel();
        EmailLogoLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        EmailLabel = new javax.swing.JLabel();
        sampleEmailLabel = new javax.swing.JLabel();
        contactLogoLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        PhoneNumberLabel = new javax.swing.JLabel();
        NumberLabel = new javax.swing.JLabel();
        MyInformationLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        MyInformationLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MyInformationLabel.setText("My Information");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        EditInfoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EditInfoLabel.setText("Edit");
        getContentPane().add(EditInfoLabel);
        EditInfoLabel.setBounds(224, 57, 30, 30);

        LeftArrowInfoLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LeftArrowInfoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\ethyl28\\src\\img\\leftArrow.png")); // NOI18N
        LeftArrowInfoLabel.setText("jLabel2");
        getContentPane().add(LeftArrowInfoLabel);
        LeftArrowInfoLabel.setBounds(30, 60, 30, 20);

        NameLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\userInfo.png")); // NOI18N
        NameLogoLabel.setText("jLabel1");
        getContentPane().add(NameLogoLabel);
        NameLogoLabel.setBounds(30, 150, 31, 32);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 190, 210, 10);

        FullNameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FullNameLabel.setText("Full Name");
        getContentPane().add(FullNameLabel);
        FullNameLabel.setBounds(80, 130, 82, 17);

        InputNameLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        InputNameLabel.setText("Laurence Castillo");
        getContentPane().add(InputNameLabel);
        InputNameLabel.setBounds(80, 160, 151, 18);

        EmailLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\Email.png")); // NOI18N
        EmailLogoLabel.setText("jLabel2");
        getContentPane().add(EmailLogoLabel);
        EmailLogoLabel.setBounds(30, 230, 40, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(40, 270, 210, 10);

        EmailLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EmailLabel.setText("Email");
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(80, 210, 44, 20);

        sampleEmailLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        sampleEmailLabel.setText("sample@gmail.com");
        getContentPane().add(sampleEmailLabel);
        sampleEmailLabel.setBounds(80, 240, 165, 18);

        contactLogoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\Kapehan\\src\\img\\phonecontact.png")); // NOI18N
        contactLogoLabel.setText("jLabel2");
        getContentPane().add(contactLogoLabel);
        contactLogoLabel.setBounds(30, 300, 36, 34);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(40, 350, 210, 10);

        PhoneNumberLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PhoneNumberLabel.setText("Phone Number");
        getContentPane().add(PhoneNumberLabel);
        PhoneNumberLabel.setBounds(80, 290, 104, 17);

        NumberLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        NumberLabel.setText("+63912345678");
        getContentPane().add(NumberLabel);
        NumberLabel.setBounds(70, 320, 151, 18);

        MyInformationLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        MyInformationLabel1.setText("My Information");
        getContentPane().add(MyInformationLabel1);
        MyInformationLabel1.setBounds(80, 60, 130, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Student.admin\\Desktop\\Ethyl\\ethyl28\\src\\img\\ea7a08282f40760a5989ba022d6f0480-removebg-preview.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 280, 549);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 240, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyInformation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyInformation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyInformation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyInformation_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyInformation_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EditInfoLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel EmailLogoLabel;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JLabel InputNameLabel;
    private javax.swing.JLabel LeftArrowInfoLabel;
    private javax.swing.JLabel MyInformationLabel;
    private javax.swing.JLabel MyInformationLabel1;
    private javax.swing.JLabel NameLogoLabel;
    private javax.swing.JLabel NumberLabel;
    private javax.swing.JLabel PhoneNumberLabel;
    private javax.swing.JLabel contactLogoLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel sampleEmailLabel;
    // End of variables declaration//GEN-END:variables
}
